image:
  file: .gitpod.dockerfile
ports:
- port: 8080
  onOpen: open-preview
- port: 3306
tasks:
- name: Terminal
  command: >
    echo "Welcome!";
    echo "Commands you can try:";
    echo " * apachectl stop";
    echo " * apachectl start";
    echo " * gp open /var/log/apache2/access.log";
    echo " * gp open /var/log/apache2/error.log";
- name: Apache & MySQL
  command: >
    cp .env.example .env;
    mysqld --initialize-insecure;
    mysqld &
    sleep 5;
    mysql -u root -e "CREATE DATABASE wordpress";
    apachectl start;
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log